"""raw documents bibliographical fields

Revision ID: 3bbdb71076fd
Revises: 9e6872fcf5f2
Create Date: 2026-07-05 15:00:29.610932
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '3bbdb71076fd'
down_revision = '9e6872fcf5f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rawdocument', sa.Column('document_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('rawdocument', sa.Column('document_author', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('rawdocument', sa.Column('document_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rawdocument', 'document_date')
    op.drop_column('rawdocument', 'document_author')
    op.drop_column('rawdocument', 'document_title')
    # ### end Alembic commands ###
