"""support evidence ledger

Revision ID: 411cd378d413
Revises: 64c066665a81
Create Date: 2026-06-20 17:39:43.625447
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '411cd378d413'
down_revision = '64c066665a81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulationevidenceledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('visibility_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pipeline', sa.JSON(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('quality_checks', sa.JSON(), nullable=False),
    sa.Column('model', sa.JSON(), nullable=False),
    sa.Column('token_usage', sa.JSON(), nullable=False),
    sa.Column('output_summary', sa.JSON(), nullable=False),
    sa.Column('raw_debug', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulationevidenceledger_agent_name'), 'simulationevidenceledger', ['agent_name'], unique=False)
    op.create_index(op.f('ix_simulationevidenceledger_sequence'), 'simulationevidenceledger', ['sequence'], unique=False)
    op.create_index(op.f('ix_simulationevidenceledger_simulation_id'), 'simulationevidenceledger', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_simulationevidenceledger_turn_index'), 'simulationevidenceledger', ['turn_index'], unique=False)
    op.create_index(op.f('ix_simulationevidenceledger_visibility_level'), 'simulationevidenceledger', ['visibility_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulationevidenceledger_visibility_level'), table_name='simulationevidenceledger')
    op.drop_index(op.f('ix_simulationevidenceledger_turn_index'), table_name='simulationevidenceledger')
    op.drop_index(op.f('ix_simulationevidenceledger_simulation_id'), table_name='simulationevidenceledger')
    op.drop_index(op.f('ix_simulationevidenceledger_sequence'), table_name='simulationevidenceledger')
    op.drop_index(op.f('ix_simulationevidenceledger_agent_name'), table_name='simulationevidenceledger')
    op.drop_table('simulationevidenceledger')
    # ### end Alembic commands ###
