"""initial schema

Revision ID: 47e6beb8360c
Revises: 
Create Date: 2026-06-06 19:33:17.735516
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '47e6beb8360c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunkingprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('strategy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunkingprofile_name'), 'chunkingprofile', ['name'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_hashed_password'), 'user', ['hashed_password'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('vectorstore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('backend', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('collection_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vectorstore_name'), 'vectorstore', ['name'], unique=True)
    op.create_table('corpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('last_edit_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['last_edit_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corpus_name'), 'corpus', ['name'], unique=True)
    op.create_table('counterpartpersonas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('last_edit_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['last_edit_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterpartpersonas_name'), 'counterpartpersonas', ['name'], unique=True)
    op.create_table('prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_name'), 'prompt', ['name'], unique=True)
    op.create_table('rawdocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_size', sa.Integer(), nullable=True),
    sa.Column('source_mtime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parsed_content', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rawdocument_name'), 'rawdocument', ['name'], unique=True)
    op.create_index(op.f('ix_rawdocument_source_path'), 'rawdocument', ['source_path'], unique=True)
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('last_edit_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['last_edit_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_name'), 'scenario', ['name'], unique=True)
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_session_token'), 'session', ['session_token'], unique=True)
    op.create_table('userrolelink',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('corpusindex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corpus_id', sa.Integer(), nullable=False),
    sa.Column('vector_store_id', sa.Integer(), nullable=False),
    sa.Column('chunking_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('vector_namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('build_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunking_profile_id'], ['chunkingprofile.id'], ),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ),
    sa.ForeignKeyConstraint(['vector_store_id'], ['vectorstore.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corpusindex_name'), 'corpusindex', ['name'], unique=True)
    op.create_index(op.f('ix_corpusindex_status'), 'corpusindex', ['status'], unique=False)
    op.create_table('corpusrawdocumentlink',
    sa.Column('corpus_id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ),
    sa.ForeignKeyConstraint(['raw_document_id'], ['rawdocument.id'], ),
    sa.PrimaryKeyConstraint('corpus_id', 'raw_document_id')
    )
    op.create_table('indexingjob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corpus_id', sa.Integer(), nullable=False),
    sa.Column('chunking_profile_id', sa.Integer(), nullable=False),
    sa.Column('vector_store_id', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_index_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_vector_namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_raw_document_id', sa.Integer(), nullable=True),
    sa.Column('current_document_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_documents', sa.Integer(), nullable=False),
    sa.Column('processed_documents', sa.Integer(), nullable=False),
    sa.Column('chunks_created', sa.Integer(), nullable=False),
    sa.Column('chunks_indexed', sa.Integer(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('candidate_corpus_index_id', sa.Integer(), nullable=True),
    sa.Column('replaced_corpus_index_id', sa.Integer(), nullable=True),
    sa.Column('failure_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_corpus_index_id'], ['corpusindex.id'], ),
    sa.ForeignKeyConstraint(['chunking_profile_id'], ['chunkingprofile.id'], ),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ),
    sa.ForeignKeyConstraint(['current_raw_document_id'], ['rawdocument.id'], ),
    sa.ForeignKeyConstraint(['replaced_corpus_index_id'], ['corpusindex.id'], ),
    sa.ForeignKeyConstraint(['vector_store_id'], ['vectorstore.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indexingjob_corpus_id'), 'indexingjob', ['corpus_id'], unique=False)
    op.create_index(op.f('ix_indexingjob_stage'), 'indexingjob', ['stage'], unique=False)
    op.create_index(op.f('ix_indexingjob_status'), 'indexingjob', ['status'], unique=False)
    op.create_table('simulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('user_id_owner', sa.Integer(), nullable=False),
    sa.Column('user_id_participant', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('corpus_id', sa.Integer(), nullable=False),
    sa.Column('corpus_index_id', sa.Integer(), nullable=False),
    sa.Column('coach_prompt_id', sa.Integer(), nullable=True),
    sa.Column('counterpart_prompt_id', sa.Integer(), nullable=True),
    sa.Column('evaluator_prompt_id', sa.Integer(), nullable=True),
    sa.Column('counter_part_side_persona_id', sa.Integer(), nullable=True),
    sa.Column('user_side', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('negotiation_state', sa.JSON(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('teacher_reviewed', sa.Boolean(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('teacher_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coach_prompt_id'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ),
    sa.ForeignKeyConstraint(['corpus_index_id'], ['corpusindex.id'], ),
    sa.ForeignKeyConstraint(['counter_part_side_persona_id'], ['counterpartpersonas.id'], ),
    sa.ForeignKeyConstraint(['counterpart_prompt_id'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['evaluator_prompt_id'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id_owner'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id_participant'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_name'), 'simulation', ['name'], unique=True)
    op.create_index(op.f('ix_simulation_status'), 'simulation', ['status'], unique=False)
    op.create_table('documentchunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.Column('chunking_profile_id', sa.Integer(), nullable=False),
    sa.Column('indexing_job_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunking_profile_id'], ['chunkingprofile.id'], ),
    sa.ForeignKeyConstraint(['indexing_job_id'], ['indexingjob.id'], ),
    sa.ForeignKeyConstraint(['raw_document_id'], ['rawdocument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indexingjobwarning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indexing_job_id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=True),
    sa.Column('document_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['indexing_job_id'], ['indexingjob.id'], ),
    sa.ForeignKeyConstraint(['raw_document_id'], ['rawdocument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indexingjobwarning_indexing_job_id'), 'indexingjobwarning', ['indexing_job_id'], unique=False)
    op.create_table('indexedchunk',
    sa.Column('corpus_index_id', sa.Integer(), nullable=False),
    sa.Column('document_chunk_id', sa.Integer(), nullable=False),
    sa.Column('external_vector_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corpus_index_id'], ['corpusindex.id'], ),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['documentchunk.id'], ),
    sa.PrimaryKeyConstraint('corpus_index_id', 'document_chunk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indexedchunk')
    op.drop_index(op.f('ix_indexingjobwarning_indexing_job_id'), table_name='indexingjobwarning')
    op.drop_table('indexingjobwarning')
    op.drop_table('documentchunk')
    op.drop_index(op.f('ix_simulation_status'), table_name='simulation')
    op.drop_index(op.f('ix_simulation_name'), table_name='simulation')
    op.drop_table('simulation')
    op.drop_index(op.f('ix_indexingjob_status'), table_name='indexingjob')
    op.drop_index(op.f('ix_indexingjob_stage'), table_name='indexingjob')
    op.drop_index(op.f('ix_indexingjob_corpus_id'), table_name='indexingjob')
    op.drop_table('indexingjob')
    op.drop_table('corpusrawdocumentlink')
    op.drop_index(op.f('ix_corpusindex_status'), table_name='corpusindex')
    op.drop_index(op.f('ix_corpusindex_name'), table_name='corpusindex')
    op.drop_table('corpusindex')
    op.drop_table('userrolelink')
    op.drop_index(op.f('ix_session_session_token'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_scenario_name'), table_name='scenario')
    op.drop_table('scenario')
    op.drop_index(op.f('ix_rawdocument_source_path'), table_name='rawdocument')
    op.drop_index(op.f('ix_rawdocument_name'), table_name='rawdocument')
    op.drop_table('rawdocument')
    op.drop_index(op.f('ix_prompt_name'), table_name='prompt')
    op.drop_table('prompt')
    op.drop_index(op.f('ix_counterpartpersonas_name'), table_name='counterpartpersonas')
    op.drop_table('counterpartpersonas')
    op.drop_index(op.f('ix_corpus_name'), table_name='corpus')
    op.drop_table('corpus')
    op.drop_index(op.f('ix_vectorstore_name'), table_name='vectorstore')
    op.drop_table('vectorstore')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_hashed_password'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_chunkingprofile_name'), table_name='chunkingprofile')
    op.drop_table('chunkingprofile')
    # ### end Alembic commands ###
