"""User email support

Revision ID: 6bf595bd3894
Revises: f8b9c0d1e2f3
Create Date: 2026-09-01 11:44:33.182808
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '6bf595bd3894'
down_revision = 'f8b9c0d1e2f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_email_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_user_user_email_address'), 'user', ['user_email_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_email_address'), table_name='user')
    op.drop_column('user', 'user_email_address')
    # ### end Alembic commands ###
