"""raw documents date to year

Revision ID: 87637f9b0af7
Revises: 3bbdb71076fd
Create Date: 2026-07-05 15:49:08.132748
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '87637f9b0af7'
down_revision = '3bbdb71076fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rawdocument', sa.Column('document_year', sa.Integer(), nullable=True))
    op.drop_column('rawdocument', 'document_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rawdocument', sa.Column('document_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('rawdocument', 'document_year')
    # ### end Alembic commands ###
