"""support scenario summaries

Revision ID: 9e6872fcf5f2
Revises: 411cd378d413
Create Date: 2026-06-20 18:54:43.825118
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9e6872fcf5f2'
down_revision = '411cd378d413'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'scenario',
        sa.Column('side_a_summary', sa.Text(), nullable=False, server_default=''),
    )
    op.add_column(
        'scenario',
        sa.Column('side_b_summary', sa.Text(), nullable=False, server_default=''),
    )
    op.alter_column('scenario', 'side_a_summary', server_default=None)
    op.alter_column('scenario', 'side_b_summary', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario', 'side_b_summary')
    op.drop_column('scenario', 'side_a_summary')
    # ### end Alembic commands ###
